
CREATE DATABASE callcenter;

USE callcenter;

CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(60) NOT NULL,
    APELLIDO VARCHAR(80) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    NACIONALIDAD VARCHAR(30) NOT NULL,
    TURNO ENUM("MATUTINO","VESPERTINO","NOCTURNO") NOT NULL,
    ADMINISTRADOR BOOLEAN NOT NULL DEFAULT '0',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (ID_USUARIO)
) ;

CREATE TABLE INCIDENCIA (
    ID_INCIDENCIA INT NOT NULL AUTO_INCREMENT,
    TIPO ENUM ("QUEJA","SUGERENCIA") NOT NULL,
    IMPORTANCIA ENUM ("EN ESPERA","URGENTE") NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    ID_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(60) NOT NULL,
    DIRECCION VARCHAR(60) NOT NULL,
    EDAD INT NOT NULL,
    TELEFONO VARCHAR(30) NULL,
    FECHA DATE NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (ID_INCIDENCIA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE MOVIMIENTO (
    ID_MOVIMIENTO INT NOT NULL AUTO_INCREMENT,
    ID_INCIDENCIA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    TIPO ENUM("ALTA","BAJA","MODIFICACION") NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (ID_MOVIMIENTO),
    FOREIGN KEY (ID_INCIDENCIA) REFERENCES INCIDENCIA(ID_INCIDENCIA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

