version: "2"
services: 
    db:
        image: mariadb:latest
        container_name: "DB"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass    
        
