/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sincronizados;

import java.awt.Color;
import java.awt.Label;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author David Delgado Hernandez 150205@upslp.edu.mx
 */
public class Colores extends javax.swing.JFrame implements Runnable{
    private Thread hilo1 = new Thread(this, "hilo1");
    private Thread hilo2 = new Thread(this, "hilo2");
    private Thread hilo3 = new Thread(this, "hilo3");
    private Thread hilo4 = new Thread(this, "manager");
    private int[] arreglo = new int[10];
    private boolean[] flags = new boolean[3];
    /**
     * Creates new form Colores
     */
    public Colores() {
        initComponents();
        color1.setBackground(Color.BLACK);
        color2.setBackground(Color.BLACK);
        color3.setBackground(Color.BLACK);        
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();
        

        
        for (int i = 0; i < 3; i++) {
            flags[i] = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color1 = new javax.swing.JLabel();
        color2 = new javax.swing.JLabel();
        color3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        color1.setOpaque(true);

        color2.setOpaque(true);

        color3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(color2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(color3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(color2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(color3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(color1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel color1;
    private javax.swing.JLabel color2;
    private javax.swing.JLabel color3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        boolean exit = true;
        try{
            if (Thread.currentThread().getName().equals("hilo1")) {                
                cambiarColor(color1,0);
            }else if(Thread.currentThread().getName().equals("hilo2")){

                cambiarColor(color2,1);
            }else if(Thread.currentThread().getName().equals("hilo3")){

                cambiarColor(color3,2);
            }else if(Thread.currentThread().getName().equals("manager")){
                for (int i = 0; i < 3; i++) {
                    if (flags[i] == false) {
                        exit = false;
                        break;
                    }
                }
                if (exit) {
                    notifyAll();
                }else{
                    exit = true;
                }
            }               
            
        }catch(InterruptedException e){
            JOptionPane.showMessageDialog(this, "Error del hilo");
        }
    }
    
    private synchronized void cambiarColor(JLabel label,int id) throws InterruptedException{
        label.setBackground(Color.yellow);
        
        for (int i = 0; i < 10; i++) {
            arreglo[i] = i;
            label.setText(String.valueOf(arreglo[i]));
            System.out.println(arreglo[i]);
            Thread.currentThread().sleep(100);
        }
        flags[id] = true;
        wait();
        label.setBackground(Color.CYAN);
    }
    
}
