/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.upslp.callcenterclient.gui;

import com.toedter.calendar.JCalendar;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;
import mx.edu.upslp.callcenterclient.gui.datos.Usuario;
import mx.edu.upslp.callcenterclient.validaciones.Validador;
import mx.edu.upslp.callserver.usuario.UsuarioEJB;

/**
 *
 * @author David Delgado Hernandez 150205@upslp.edu.mx
 */
public class administradorFrame extends javax.swing.JFrame {
    private UsuarioEJB miUsuario;
    private Validador validador = new Validador();
    private JCalendar calendario = new JCalendar();
    private String[] usuariosTitle = new String[] {"Username","Nombre","Apellido"};
    private Usuario usuarioManager = new Usuario();
    // modificamos el modelo en su creacion
    private DefaultTableModel usuariosModel = new DefaultTableModel(){
        boolean[] editColum = {false,false,false};
        // hacemos que las columnas no sea editables
        public boolean isCellEditable(int indFila,int indCol){
            return editColum[indCol];
        }
    };

    
    /**
     * Creates new form administradorFrame
     */
    public administradorFrame(UsuarioEJB miUsuario) {
        this.miUsuario = miUsuario;
        initComponents();
        // agregar el calendario a pantalla
        calendario.setEnabled(true);
        calendario.setVisible(true);
        calendarPanel.setLayout(new BoxLayout(calendarPanel, View.Y_AXIS));
        calendarPanel.add(calendario);
        
        // crear su manejador de eventos
        
        calendario.setMaxSelectableDate(new Date());
                
        
        
        this.setResizable(false);
        this.setTitle("Asistencia de Quejas y sugerencias");
        this.setLocationRelativeTo(null);
        
        // ocultar letros de warning de la primera tab
        wnombreLabel.setVisible(false);
        wapellidoLabel.setVisible(false);
        wnacionalidadLabel.setVisible(false);
        wcorreoLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        tabs = new javax.swing.JTabbedPane();
        altasPanel = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        apellidoField = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        turnoLabel = new javax.swing.JLabel();
        turnoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nacionalidadLabel = new javax.swing.JLabel();
        enviarButton = new javax.swing.JButton();
        accesoCombo = new javax.swing.JComboBox<>();
        wnombreLabel = new javax.swing.JLabel();
        wapellidoLabel = new javax.swing.JLabel();
        nacionalidadField = new javax.swing.JTextField();
        wnacionalidadLabel = new javax.swing.JLabel();
        calendarPanel = new javax.swing.JPanel();
        correoLabel = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        wcorreoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportesTable = new javax.swing.JTable();
        listaLabel = new javax.swing.JLabel();
        anteriorButton = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        usuariosTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();
        usuariosLabel = new javax.swing.JLabel();
        usuariosAnteriorButton = new javax.swing.JButton();
        usuariosSiguienteButton = new javax.swing.JButton();
        usuariosNombreLabel = new javax.swing.JLabel();
        usuariosNombreField = new javax.swing.JTextField();
        usuariosApellidoLabel = new javax.swing.JLabel();
        usuariosApellidoField = new javax.swing.JTextField();
        usuariosFechaLabel = new javax.swing.JLabel();
        usuariosFechaField = new javax.swing.JTextField();
        usuariosNacionalidadLabel = new javax.swing.JLabel();
        usuariosNacionalidadField = new javax.swing.JTextField();
        usuariosTurnoLabel = new javax.swing.JLabel();
        usuariosAccesoLabel = new javax.swing.JLabel();
        usuariosAccesoField = new javax.swing.JTextField();
        usuariosCreacionLabel = new javax.swing.JLabel();
        usuariosCreacionField = new javax.swing.JTextField();
        usuariosActualizacionLabel = new javax.swing.JLabel();
        usuariosActualizacionField = new javax.swing.JTextField();
        seguridadPanel = new javax.swing.JPanel();
        seguridadLabel = new javax.swing.JLabel();
        usuariosPasswordLabel = new javax.swing.JLabel();
        usuariosPasswordField = new javax.swing.JPasswordField();
        usuariosDeleteLabel = new javax.swing.JLabel();
        usuariosDeleteButton = new javax.swing.JButton();
        actualizarPasswordButton = new javax.swing.JButton();
        usuariosTurnoField = new javax.swing.JTextField();

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        altasPanel.setName("altas"); // NOI18N

        nombreLabel.setText("Nombre");

        nombreField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFieldFocusLost(evt);
            }
        });

        apellidoLabel.setText("Apellido");

        apellidoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidoFieldFocusLost(evt);
            }
        });

        fechaLabel.setText("Fecha de Nacimiento");

        turnoLabel.setText("Turno");

        turnoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"MATUTINO","VESPERTINO","NOCTURNO"}));

        jLabel5.setText("Nivel de Acceso");

        nacionalidadLabel.setText("Nacionalidad");

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        accesoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"GESTOR","ADMINISTRADOR"}));

        wnombreLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wnombreLabel.setForeground(new java.awt.Color(255, 0, 0));
        wnombreLabel.setText("*Nombre Invalido");

        wapellidoLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wapellidoLabel.setForeground(new java.awt.Color(255, 0, 0));
        wapellidoLabel.setText("* Apellido Invalido");

        nacionalidadField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nacionalidadFieldFocusLost(evt);
            }
        });

        wnacionalidadLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wnacionalidadLabel.setForeground(new java.awt.Color(255, 0, 0));
        wnacionalidadLabel.setText("* Nacionalidad Invalida");

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        calendarPanelLayout.setVerticalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        correoLabel.setText("Correo");

        correoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoFieldFocusLost(evt);
            }
        });

        wcorreoLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wcorreoLabel.setForeground(new java.awt.Color(255, 0, 0));
        wcorreoLabel.setText("* Correo Invalido");

        javax.swing.GroupLayout altasPanelLayout = new javax.swing.GroupLayout(altasPanel);
        altasPanel.setLayout(altasPanelLayout);
        altasPanelLayout.setHorizontalGroup(
            altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wapellidoLabel)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(altasPanelLayout.createSequentialGroup()
                        .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(wnombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wnacionalidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nacionalidadField)
                            .addComponent(turnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(turnoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(nacionalidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accesoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(correoLabel)
                            .addComponent(correoField)
                            .addComponent(wcorreoLabel))))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        altasPanelLayout.setVerticalGroup(
            altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(turnoLabel))
                .addGap(18, 18, 18)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(wnombreLabel)
                .addGap(2, 2, 2)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoLabel)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(wapellidoLabel)
                .addGap(1, 1, 1)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(nacionalidadLabel))
                .addGap(18, 18, 18)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altasPanelLayout.createSequentialGroup()
                        .addComponent(nacionalidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wnacionalidadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(correoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wcorreoLabel)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarButton)
                .addGap(100, 100, 100))
        );

        tabs.addTab("Altas", altasPanel);

        jPanel2.setName("reportes"); // NOI18N

        reportesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportesTable);

        listaLabel.setText("Lista de reportes");

        anteriorButton.setText("Anterior");

        siguienteButton.setText("Siguiente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(listaLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(anteriorButton)
                        .addGap(18, 18, 18)
                        .addComponent(siguienteButton)))
                .addContainerGap(684, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(listaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorButton)
                    .addComponent(siguienteButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tabs.addTab("Reportes", jPanel2);

        jPanel3.setName("estadisticas"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1143, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        tabs.addTab("Estadisticas", jPanel3);

        usuariosTab.setName("listaUsuarios"); // NOI18N

        usuariosTable.setModel(usuariosModel);
        usuariosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariosTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(usuariosTable);

        usuariosLabel.setText("Lista de Usuarios");

        usuariosAnteriorButton.setText("Anterior");

        usuariosSiguienteButton.setText("Siguiente");

        usuariosNombreLabel.setText("Nombre");

        usuariosNombreField.setEditable(false);

        usuariosApellidoLabel.setText("Apellido");

        usuariosApellidoField.setEditable(false);

        usuariosFechaLabel.setText("Fecha de Nacimiento");

        usuariosFechaField.setEditable(false);

        usuariosNacionalidadLabel.setText("Nacionalidad");

        usuariosNacionalidadField.setEditable(false);

        usuariosTurnoLabel.setText("Turno");

        usuariosAccesoLabel.setText("Nivel de acceso");

        usuariosAccesoField.setEditable(false);

        usuariosCreacionLabel.setText("Fecha de Creacion");

        usuariosCreacionField.setEditable(false);

        usuariosActualizacionLabel.setText("Ultima Actualizacion");

        usuariosActualizacionField.setEditable(false);

        seguridadPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        seguridadLabel.setText("Area de Seguridad");

        usuariosPasswordLabel.setText("Cambiar Contraseña");

        usuariosDeleteLabel.setText("Eliminar Usuario");

        usuariosDeleteButton.setText("Eliminar");
        usuariosDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosDeleteButtonActionPerformed(evt);
            }
        });

        actualizarPasswordButton.setText("Actualizar");
        actualizarPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seguridadPanelLayout = new javax.swing.GroupLayout(seguridadPanel);
        seguridadPanel.setLayout(seguridadPanelLayout);
        seguridadPanelLayout.setHorizontalGroup(
            seguridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seguridadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seguridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seguridadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(seguridadPanelLayout.createSequentialGroup()
                        .addComponent(usuariosPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuariosDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(seguridadPanelLayout.createSequentialGroup()
                        .addGroup(seguridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualizarPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(seguridadPanelLayout.createSequentialGroup()
                                .addComponent(usuariosPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(usuariosDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        seguridadPanelLayout.setVerticalGroup(
            seguridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seguridadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seguridadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seguridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariosPasswordLabel)
                    .addComponent(usuariosDeleteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seguridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariosPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuariosDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actualizarPasswordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuariosTurnoField.setEditable(false);

        javax.swing.GroupLayout usuariosTabLayout = new javax.swing.GroupLayout(usuariosTab);
        usuariosTab.setLayout(usuariosTabLayout);
        usuariosTabLayout.setHorizontalGroup(
            usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosTabLayout.createSequentialGroup()
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuariosNombreLabel)
                            .addComponent(usuariosNombreField)
                            .addComponent(usuariosApellidoLabel)
                            .addComponent(usuariosApellidoField)
                            .addComponent(usuariosFechaLabel)
                            .addComponent(usuariosFechaField)
                            .addComponent(usuariosNacionalidadLabel)
                            .addComponent(usuariosNacionalidadField)
                            .addComponent(usuariosTurnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuariosAccesoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(usuariosAccesoField)
                            .addComponent(usuariosTurnoField))
                        .addGap(32, 32, 32)
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(usuariosTabLayout.createSequentialGroup()
                                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuariosCreacionField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usuariosCreacionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuariosActualizacionLabel)
                                    .addComponent(usuariosActualizacionField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(seguridadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(usuariosTabLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(usuariosLabel))
                    .addGroup(usuariosTabLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(usuariosAnteriorButton)
                        .addGap(34, 34, 34)
                        .addComponent(usuariosSiguienteButton)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        usuariosTabLayout.setVerticalGroup(
            usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(usuariosTabLayout.createSequentialGroup()
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuariosNombreLabel)
                            .addComponent(usuariosCreacionLabel)
                            .addComponent(usuariosActualizacionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuariosNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariosCreacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariosActualizacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuariosApellidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuariosApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuariosFechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usuariosTabLayout.createSequentialGroup()
                                .addComponent(usuariosFechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuariosNacionalidadLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuariosNacionalidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuariosTurnoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuariosTurnoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(usuariosAccesoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuariosAccesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(seguridadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariosSiguienteButton)
                    .addComponent(usuariosAnteriorButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabs.addTab("Lista de Usuarios", usuariosTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        boolean valid = true;
        boolean administrador;
        Date fecha;
        Usuario usuario = new Usuario();
        // validar los datos
        if (!validador.isAlphaSpace(nombreField.getText()) || nombreField.getText().length() == 0) {
            valid = false;
            wnombreLabel.setVisible(true);            
        }else{
            usuario.setNombre(nombreField.getText());
        }
        
        if (!validador.isAlphaSpace(apellidoField.getText()) || apellidoField.getText().length() == 0) {
            valid = false;
            wapellidoLabel.setVisible(true);            
        }else{
            usuario.setApellido(apellidoField.getText());
        }
        
        if (!validador.isAlpha(nacionalidadField.getText()) || nacionalidadField.getText().length() == 0) {
            valid = false;
            wnacionalidadLabel.setVisible(true);            
        }else{
            usuario.setNacionalidad(nacionalidadField.getText());
        }
        
        if (!validador.isEmail(correoField.getText())) {
            wcorreoLabel.setVisible(true);
            valid = false;
        }else{
            usuario.setCorreo(correoField.getText());            
        }
        
        if (valid) {
            // las demas validaciones pasaron
            fecha = new Date(calendario.getYearChooser().getYear(),
                    calendario.getMonthChooser().getMonth(),
                    calendario.getDayChooser().getDay()
            );
            
            usuario.setFechaNacimiento(fecha);
            
            if (accesoCombo.getSelectedIndex() == 0) {
                administrador = false;
            }
            else{
                administrador = true;
            }                        
            usuario.setAdministrador(Boolean.valueOf(administrador));
            
            if (turnoCombo.getSelectedIndex() == 0) {
                usuario.setTurno("MATUTINO");
            }else if (turnoCombo.getSelectedIndex() == 1) {
                usuario.setTurno("VESPERTINO");
            }else{
                usuario.setTurno("NOCTURNO");
            }
            
            if (usuario.registro() == null) {
                JOptionPane.showMessageDialog(null, "Error al crear el usuario revisa los datos por favor");
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario creado con exito\nUsername: " +
                        usuario.getUsername() + 
                        "\nPassword: " + usuario.getPassword());
            }            
        }else{
            JOptionPane.showMessageDialog(this, "Los datos ingresados son invalidos");
        }
                
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        
        if (tabs.getSelectedComponent().getName().equals("listaUsuarios")) {
            // consultar la lista de usuarios
            usuariosModel.setDataVector(usuarioManager.obtenerDatos(true), usuariosTitle);            
        }
    }//GEN-LAST:event_tabsStateChanged

    private void usuariosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosTableMouseClicked
        // al hacer click sobre algun componente obtener la informacion del usuario
        UsuarioEJB usuarioSel = usuarioManager.obtenerDatosUsuario(usuariosTable.getSelectedRow());
        // el usuario existe llenar los campos
        if (usuarioSel != null) {
            usuariosNombreField.setText(usuarioSel.getNombre());
            usuariosApellidoField.setText(usuarioSel.getApellido());
            usuariosNacionalidadField.setText(usuarioSel.getNacionalidad());
            usuariosTurnoField.setText(usuarioSel.getTurno());
            if (usuarioSel.isAdministrador()) {
                usuariosAccesoField.setText("ADMINISTRADOR");
            }
            else{
                usuariosAccesoField.setText("GESTOR");
            }
            // fechas
            usuariosFechaField.setText(usuarioSel.getFechaNacimiento().toString());
            usuariosCreacionField.setText(usuarioSel.getCreatedAt().toString());
            usuariosActualizacionField.setText(usuarioSel.getUpdatedAt().toString());
        }
        
        
    }//GEN-LAST:event_usuariosTableMouseClicked

    private void actualizarPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPasswordButtonActionPerformed
        // cambiar la contraseña                
        if (usuariosTable.getSelectedRow() != -1 && usuariosPasswordField.getText().length() > 0) {
            // obtener el usuario
            UsuarioEJB objetivo = usuarioManager.obtenerDatosUsuario(usuariosTable.getSelectedRow());
            objetivo.setPassword(usuariosPasswordField.getText());
            usuarioManager.actualizarUsuario(objetivo);            
            JOptionPane.showMessageDialog(null, "Contraseña actualizada correctamente");
            usuariosPasswordField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario para realizar esta accion");
        }
    }//GEN-LAST:event_actualizarPasswordButtonActionPerformed

    private void usuariosDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosDeleteButtonActionPerformed
        // eliminar el usuario
        if (usuariosTable.getSelectedRow() != -1 ) {
            // obtener el id del usuario 
            String id = usuarioManager.obtenerDatosUsuario(usuariosTable.getSelectedRow()).getIdUsuario();
            // remover        
            int resp = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este usuario?");
            
            if (resp == 0) {
                if (usuarioManager.removerUsuario(id)) {
                    JOptionPane.showMessageDialog(null, "Usuario removido con exito");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al remover al usuario");
                }
                // regenerar la tabla
                usuariosModel.setDataVector(usuarioManager.obtenerDatos(true), usuariosTitle);
            }            
        }       
    }//GEN-LAST:event_usuariosDeleteButtonActionPerformed

    private void correoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFieldFocusLost
        // validar el correo
        if (validador.isEmail(correoField.getText())) {
            wcorreoLabel.setVisible(false);
        }else{
            wcorreoLabel.setVisible(true);
        }
    }//GEN-LAST:event_correoFieldFocusLost

    private void nombreFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusLost
        // TODO add your handling code here:
        if (validador.isAlphaSpace(nombreField.getText())) {
           wnombreLabel.setVisible(false);
        }else{
           wnombreLabel.setVisible(true);
        }        
    }//GEN-LAST:event_nombreFieldFocusLost

    private void apellidoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidoFieldFocusLost
        // TODO add your handling code here:
        if (validador.isAlphaSpace(apellidoField.getText())) {
           wapellidoLabel.setVisible(false);
        }else{
           wapellidoLabel.setVisible(true);
        }         
    }//GEN-LAST:event_apellidoFieldFocusLost

    private void nacionalidadFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nacionalidadFieldFocusLost
        // TODO add your handling code here:
        if (validador.isAlpha(nacionalidadField.getText())) {
            wnacionalidadLabel.setVisible(false);
        }
        else{
            wnacionalidadLabel.setVisible(true);
        }        
    }//GEN-LAST:event_nacionalidadFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accesoCombo;
    private javax.swing.JButton actualizarPasswordButton;
    private javax.swing.JPanel altasPanel;
    private javax.swing.JButton anteriorButton;
    private javax.swing.JTextField apellidoField;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel listaLabel;
    private javax.swing.JTextField nacionalidadField;
    private javax.swing.JLabel nacionalidadLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTable reportesTable;
    private javax.swing.JLabel seguridadLabel;
    private javax.swing.JPanel seguridadPanel;
    private javax.swing.JButton siguienteButton;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JComboBox<String> turnoCombo;
    private javax.swing.JLabel turnoLabel;
    private javax.swing.JTextField usuariosAccesoField;
    private javax.swing.JLabel usuariosAccesoLabel;
    private javax.swing.JTextField usuariosActualizacionField;
    private javax.swing.JLabel usuariosActualizacionLabel;
    private javax.swing.JButton usuariosAnteriorButton;
    private javax.swing.JTextField usuariosApellidoField;
    private javax.swing.JLabel usuariosApellidoLabel;
    private javax.swing.JTextField usuariosCreacionField;
    private javax.swing.JLabel usuariosCreacionLabel;
    private javax.swing.JButton usuariosDeleteButton;
    private javax.swing.JLabel usuariosDeleteLabel;
    private javax.swing.JTextField usuariosFechaField;
    private javax.swing.JLabel usuariosFechaLabel;
    private javax.swing.JLabel usuariosLabel;
    private javax.swing.JTextField usuariosNacionalidadField;
    private javax.swing.JLabel usuariosNacionalidadLabel;
    private javax.swing.JTextField usuariosNombreField;
    private javax.swing.JLabel usuariosNombreLabel;
    private javax.swing.JPasswordField usuariosPasswordField;
    private javax.swing.JLabel usuariosPasswordLabel;
    private javax.swing.JButton usuariosSiguienteButton;
    private javax.swing.JPanel usuariosTab;
    private javax.swing.JTable usuariosTable;
    private javax.swing.JTextField usuariosTurnoField;
    private javax.swing.JLabel usuariosTurnoLabel;
    private javax.swing.JLabel wapellidoLabel;
    private javax.swing.JLabel wcorreoLabel;
    private javax.swing.JLabel wnacionalidadLabel;
    private javax.swing.JLabel wnombreLabel;
    // End of variables declaration//GEN-END:variables
}
