/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.upslp.callcenterclient.gui;

import com.toedter.calendar.JCalendar;
import java.awt.event.KeyListener;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.text.View;
import mx.edu.upslp.callcenterclient.validaciones.Validador;

/**
 *
 * @author David Delgado Hernandez 150205@upslp.edu.mx
 */
public class administradorFrame extends javax.swing.JFrame {
    private Validador validador = new Validador();
    private JCalendar calendario = new JCalendar();
    /**
     * Creates new form administradorFrame
     */
    public administradorFrame() {
        initComponents();
        // agregar el calendario a pantalla
        calendario.setEnabled(true);
        calendario.setVisible(true);
        calendarPanel.setLayout(new BoxLayout(calendarPanel, View.Y_AXIS));
        calendarPanel.add(calendario);
        
        // crear su manejador de eventos
        
        calendario.setMaxSelectableDate(new Date());
                
        
        
        this.setResizable(false);
        this.setTitle("Asistencia de Quejas y sugerencias");
        this.setLocationRelativeTo(null);
        
        // ocultar letros de warning de la primera tab
        wnombreLabel.setVisible(false);
        wapellidoLabel.setVisible(false);
        wnacionalidadLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reportes = new javax.swing.JTabbedPane();
        altasPanel = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        apellidoField = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        turnoLabel = new javax.swing.JLabel();
        turnoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nacionalidadLabel = new javax.swing.JLabel();
        enviarButton = new javax.swing.JButton();
        accesoCombo = new javax.swing.JComboBox<>();
        wnombreLabel = new javax.swing.JLabel();
        wapellidoLabel = new javax.swing.JLabel();
        nacionalidadField = new javax.swing.JTextField();
        wnacionalidadLabel = new javax.swing.JLabel();
        calendarPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportesTable = new javax.swing.JTable();
        listaLabel = new javax.swing.JLabel();
        anteriorButton = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreLabel.setText("Nombre");

        nombreField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreFieldKeyTyped(evt);
            }
        });

        apellidoLabel.setText("Apellido");

        apellidoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoFieldKeyTyped(evt);
            }
        });

        fechaLabel.setText("Fecha de Nacimiento");

        turnoLabel.setText("Turno");

        turnoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"MATUTINO","VESPERTINO","NOCTURNO"}));

        jLabel5.setText("Nivel de Acceso");

        nacionalidadLabel.setText("Nacionalidad");

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        accesoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"GESTOR","ADMINISTRADOR"}));

        wnombreLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wnombreLabel.setForeground(new java.awt.Color(255, 0, 0));
        wnombreLabel.setText("*Nombre Invalido");

        wapellidoLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wapellidoLabel.setForeground(new java.awt.Color(255, 0, 0));
        wapellidoLabel.setText("* Apellido Invalido");

        nacionalidadField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nacionalidadFieldKeyTyped(evt);
            }
        });

        wnacionalidadLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        wnacionalidadLabel.setForeground(new java.awt.Color(255, 0, 0));
        wnacionalidadLabel.setText("* Nacionalidad Invalida");

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        calendarPanelLayout.setVerticalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout altasPanelLayout = new javax.swing.GroupLayout(altasPanel);
        altasPanel.setLayout(altasPanelLayout);
        altasPanelLayout.setHorizontalGroup(
            altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wapellidoLabel)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(altasPanelLayout.createSequentialGroup()
                        .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(wnombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wnacionalidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nacionalidadField)
                            .addComponent(turnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(turnoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(nacionalidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accesoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        altasPanelLayout.setVerticalGroup(
            altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(turnoLabel))
                .addGap(18, 18, 18)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(wnombreLabel)
                .addGap(2, 2, 2)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoLabel)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(wapellidoLabel)
                .addGap(1, 1, 1)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(nacionalidadLabel))
                .addGap(18, 18, 18)
                .addGroup(altasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altasPanelLayout.createSequentialGroup()
                        .addComponent(nacionalidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wnacionalidadLabel)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarButton)
                .addGap(100, 100, 100))
        );

        Reportes.addTab("Altas", altasPanel);

        reportesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportesTable);

        listaLabel.setText("Lista de reportes");

        anteriorButton.setText("Anterior");

        siguienteButton.setText("Siguiente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(listaLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(anteriorButton)
                        .addGap(18, 18, 18)
                        .addComponent(siguienteButton)))
                .addContainerGap(672, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(listaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorButton)
                    .addComponent(siguienteButton))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Reportes.addTab("Reportes", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1131, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        Reportes.addTab("Estadisticas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reportes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reportes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreFieldKeyTyped
        if (validador.isAlphaSpace(nombreField.getText())) {
           wnombreLabel.setVisible(false);
        }else{
           wnombreLabel.setVisible(true);
        }
    }//GEN-LAST:event_nombreFieldKeyTyped

    private void apellidoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoFieldKeyTyped
        if (validador.isAlphaSpace(apellidoField.getText())) {
           wapellidoLabel.setVisible(false);
        }else{
           wapellidoLabel.setVisible(true);
        } 
    }//GEN-LAST:event_apellidoFieldKeyTyped

    private void nacionalidadFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nacionalidadFieldKeyTyped
        if (validador.isAlpha(nacionalidadField.getText())) {
            wnacionalidadLabel.setVisible(false);
        }
        else{
            wnacionalidadLabel.setVisible(true);
        }
    }//GEN-LAST:event_nacionalidadFieldKeyTyped

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        
        // validar los datos
        
        
        
        
        
        
    }//GEN-LAST:event_enviarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Reportes;
    private javax.swing.JComboBox<String> accesoCombo;
    private javax.swing.JPanel altasPanel;
    private javax.swing.JButton anteriorButton;
    private javax.swing.JTextField apellidoField;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaLabel;
    private javax.swing.JTextField nacionalidadField;
    private javax.swing.JLabel nacionalidadLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTable reportesTable;
    private javax.swing.JButton siguienteButton;
    private javax.swing.JComboBox<String> turnoCombo;
    private javax.swing.JLabel turnoLabel;
    private javax.swing.JLabel wapellidoLabel;
    private javax.swing.JLabel wnacionalidadLabel;
    private javax.swing.JLabel wnombreLabel;
    // End of variables declaration//GEN-END:variables
}
